export const REQUEST_GET_ANIMALS = 'REQUEST_GET_ANIMALS';
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS';
export const GET_ANIMALS_FAILED = 'GET_ANIMALS_FAILED';

export const REQUEST_CREATE_ANIMAL = 'REQUEST_CREATE_ANIMAL';
export const CREATE_ANIMAL_SUCCESS = 'CREATE_ANIMAL_SUCCESS';
export const CREATE_ANIMAL_FAILED = 'CREATE_ANIMAL_FAILED';

export const REQUEST_EDIT_ANIMAL = 'REQUEST_EDIT_ANIMAL';
export const EDIT_ANIMAL_SUCCESS = 'EDIT_ANIMAL_SUCCESS';
export const EDIT_ANIMAL_FAILED = 'EDIT_ANIMAL_FAILED';

export const REQUEST_DELETE_ANIMAL = 'REQUEST_DELETE_ANIMAL';
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS';
export const DELETE_ANIMAL_FAILED = 'DELETE_ANIMAL_FAILED';
