export const CHANGE_TEXT_FILTER = 'CHANGE_TEXT_FILTER';
export const CHANGE_MIN_PRICE_FILTER = 'CHANGE_MIN_PRICE_FILTER ';
export const CHANGE_MAX_PRICE_FILTER = 'CHANGE_MAX_PRICE_FILTER ';
export const CHANGE_MIN_DATE_FILTER = 'CHANGE_MIN_DATE_FILTER ';
export const CHANGE_MAX_DATE_FILTER = 'CHANGE_MAX_DATE_FILTER ';
