export const CHANGE_FILTER_TEXT = 'CHANGE_FILTER_TEXT';
export const CHANGE_FILTER_PRICE = 'CHANGE_FILTER_PRICE';
export const CHANGE_FILTER_DATE = 'CHANGE_FILTER_DATE';
export const CHANGE_FILTER_SORT = 'CHANGE_FILTER_SORT';
