export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const REQUEST_EDIT_USER = 'REQUEST_EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const REQUEST_UPLOAD_USER_IMAGE = 'REQUEST_UPLOAD_USER_IMAGE';
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const UPLOAD_USER_IMAGE_FAILED = 'UPLOAD_USER_IMAGE_FAILED';

export const ADD_USER = 'ADD_USER';
